[package]
name = "todo-list"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
console = "0.15.8"
dialoguer = "0.11.0"
eframe = "0.29.1"
egui = "0.29.1"
egui_extras = "0.29.1"
env_logger = "0.11.5"
fmt = "0.1.0"
rusqlite = "0.32.1"
strum = "0.26.3"
tui = "0.19.0"
